# Generated by Django 4.2.1 on 2023-05-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postname',
        ),
        migrations.AddField(
            model_name='post',
            name='petimage',
            field=models.ImageField(blank=True, upload_to='pets'),
        ),
    ]
