# Generated by Django 4.2.1 on 2023-05-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_pet', '0002_remove_post_postname_post_petimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='petname',
            new_name='postname',
        ),
    ]
